server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp
    username: root
    password: root@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
